export const GET_FEEDBACK_SUCCESS = 'GET_FEEDBACK_SUCCESS'

export const POST_FEEDBACK_SUCCESS = 'POST_FEEDBACK_SUCCESS'

export const UPDATE_TEXT = 'UPDATETEXTT'
export const UPDATE_RATING = 'UPDATE_RATING'
export const RESET_TEXT_RATING = 'RESET_TEXT_RATING'